In [ ]:
pip install numpy

In [2]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [10]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)   
print(arr2.shape) 

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [8]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3[1])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]


In [ ]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,45])
np.mean(arr4)
np.max(arr4)
np.min(arr4)
np.median(arr4)
np.sum(arr4)



np.int64(100)

In [26]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.subtract(arr1,arr2)
np.add(arr1,arr2)

array([5, 7, 9])

In [19]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,45])
print(arr4[3])

4
